name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-change-files:
    runs-on: ubuntu-latest
    name: Build and run lint

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
